{
 "title": "NT5000",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Harvest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy Today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nt5000_energy_day" }
   ]
  },
  {
   "title": "Energy Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nt5000_energy_total" }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "DC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nt5000_dc_voltage" },
    { "expr": "nt5000_dc_current" },
    { "expr": "nt5000_dc_power" }
   ]
  },
  {
   "title": "AC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "nt5000_ac_voltage" },
    { "expr": "nt5000_ac_current" },
    { "expr": "nt5000_ac_power" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "nt5000_temperature" }
   ]
  },
  {
   "title": "Heat Flux",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    { "expr": "nt5000_heat_flux" }
   ]
  }
 ]
}